import { mkdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { join, relative, resolve } from 'node:path'
import type { App } from './app.ts'
import { buildOpenApi } from './facets/openapi.ts'
import { inspectAll } from './inspect.ts'
import { buildManifest, type Manifest } from './manifest.ts'
import { buildSdk } from './sdk.ts'

function llmsTxt(app: App, manifest: Manifest): string {
  const inspection = inspectAll(app, manifest)
  const lines = [`# ${manifest.name}`, '', `> ${manifest.description ?? `${manifest.name} API`}`, '']
  const web = manifest.web ? `, and a web console (${manifest.web.path})` : ''
  lines.push(
    `Reachable as a REST API (OpenAPI at /openapi.json), an MCP server (/mcp), a CLI, and a TypeScript SDK${web}. Every operation behaves the same on all of them.`,
    '',
    '## Operations',
    '',
  )
  for (const op of inspection.ops) {
    const traits = Object.entries(op.traits).map(([k, v]) => (v === true ? k : `${k}=${v}`))
    lines.push(`### ${op.id}`, '', op.description ?? '', '')
    if (traits.length) lines.push(`Traits: ${traits.join(', ')}`, '')
    if (op.rest) lines.push(`- REST: \`${op.rest.method} ${op.rest.path}\``)
    if (op.cli) lines.push(`- CLI: \`${op.cli.snippet}\``)
    if (op.mcp) lines.push(`- MCP tool: \`${op.mcp.tool.name}\``)
    if (op.sdk) lines.push(`- SDK: \`${op.sdk.snippet.split('\n')[0]}\``)
    if (op.web) lines.push(`- Web: ${op.web.screen.kind} at \`${manifest.web?.path ?? ''}${op.web.screen.path}\``)
    lines.push('')
  }
  return lines.join('\n')
}

// The generated CLI package depends on the engine that runs it. `facet` and `@omniface/cli` version in
// lockstep, so this package's own version is the range to ask for.
const { version: FACET_VERSION } = createRequire(import.meta.url)('../package.json') as { version: string }

export type BuildResult = { outDir: string; files: string[] }

export type BuildOptions = {
  /** What the generated packages import the shared runtime from. Tests point it at the workspace. */
  engineImport?: string
  clientImport?: string
}

/**
 * Outputs only what runs elsewhere (docs/README.md, principle 6): the manifest, OpenAPI, llms.txt,
 * and a CLI package = the shared engine + an embedded manifest + a bin named after the app.
 */
export async function build(app: App, outDir: string, options: BuildOptions = {}): Promise<BuildResult> {
  const manifest = buildManifest(app)
  const root = resolve(outDir)
  const files: Record<string, string> = {
    'manifest.json': JSON.stringify(manifest, null, 2) + '\n',
    'openapi.json': JSON.stringify(buildOpenApi(manifest), null, 2) + '\n',
    'llms.txt': llmsTxt(app, manifest),
  }
  if (manifest.sdk) {
    Object.assign(files, buildSdk(manifest, { clientImport: options.clientImport, facetVersion: FACET_VERSION }))
  }
  if (manifest.cli) {
    const bin = manifest.cli.binName
    files['cli/manifest.json'] = files['manifest.json']!
    files['cli/package.json'] =
      JSON.stringify(
        {
          name: `${bin}-cli`,
          version: manifest.version,
          description: `${manifest.name} command-line interface (generated by facet)`,
          type: 'module',
          bin: { [bin]: './bin.mjs' },
          dependencies: { '@omniface/cli': `^${FACET_VERSION}` },
        },
        null,
        2,
      ) + '\n'
    files['cli/bin.mjs'] = [
      '#!/usr/bin/env node',
      '// Generated by `omniface build`. Do not edit: change the app definition and rebuild.',
      `import { runCli } from '${options.engineImport ?? '@omniface/cli'}'`,
      "import manifest from './manifest.json' with { type: 'json' }",
      '',
      `process.exitCode = await runCli({ manifest, binName: ${JSON.stringify(bin)}, argv: process.argv.slice(2), io: { prompt } })`,
      '',
      'async function prompt(question) {',
      "  const { createInterface } = await import('node:readline/promises')",
      '  const rl = createInterface({ input: process.stdin, output: process.stderr })',
      '  try { return await rl.question(question) } finally { rl.close() }',
      '}',
      '',
    ].join('\n')
  }
  for (const [name, content] of Object.entries(files)) {
    const path = join(root, name)
    await mkdir(join(path, '..'), { recursive: true })
    await writeFile(path, content, name.endsWith('bin.mjs') ? { mode: 0o755 } : undefined)
  }
  return { outDir: root, files: Object.keys(files).map((f) => relative(process.cwd(), join(root, f))) }
}
